language: node_js
node_js:
  - '12'
branches:
  only:
  - master
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@10.1.6
script:
  - npm ci
  - npm run build
after_success:
  - firebase deploy
