language: node_js
node_js:
  - '9'
branches:
  only:
  - master
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@7.2.1
script:
  - npm install
  - npm run build
after_success:
  - firebase deploy
