language: node_js
node_js:
  - '8'
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@1.7.3
script:
  - echo 'Deploying...'
  - npm install
  - npm run build
after_success:
  - firebase deploy